### ISSUE TITLE
[systemd-profiles] live-session bootup hangs due network issue

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#36]
Somehow we have an ntpd service issue. This service simply fails to start. Also it seems we have some other issue makeing the bootup hang. Might be mirror related or any other service trying to connect to the internet.

However, if you disable network it boots up as normal. Have to check if we have the same issue also with ManjaroISO.

**Comment by udeved** [comment]
The hang was likely caused by pacman-boot?
Also on openrc, I had this hang when pacman was syncing, depending what mirror you caught, it was between fast and terribly slow.
I think its good you removed the service from livecd repo.

Is network up on systemd when it tries to start ntpd?

**Comment by manjaro** [comment]
![manjaro-accountsservice-systemd](https://cloud.githubusercontent.com/assets/5167332/5822847/d8329f60-a0d7-11e4-83a7-d3e2d735d992.jpg)

Somehow ntpd gets started with network-manager-dispatcher-ntpd to often. Something is up with network ...

**Comment by manjaro** [comment]
From the screenshot you see that ntpd fails somehow. Also you see it waits for plymouth to quit and actually hangs with starting lightdm. Hmm.

**Comment by udeved** [comment]
What's that network time service?
Is this a systemd specific voodoo?
Does ntpd start if you disable this network time service?

I recall other network services fail if you enable network on systemd.

**Comment by Kirek** [comment]
Network Time Service is just the description in the ntpd daemon service file

[Unit]
Description=Network Time Service
After=network.target nss-lookup.target
Conflicts=systemd-timesyncd.service

[Service]
Type=forking
PrivateTmp=true
ExecStart=/usr/bin/ntpd -g -u ntp:ntp
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by udeved** [comment]
So ntpd is started twice on systemd?

**Comment by manjaro** [comment]
Well I enabled it by systemd service and it gets also started by the dispatcher. Will disable my systemd linkage now. This is the other error I get. Doesn't matter if I use the normal or the plymouth service:
![systemd-error](https://cloud.githubusercontent.com/assets/5167332/5823409/c98caf78-a0dc-11e4-8fd0-e1e4bf0f0fda.jpg)

**Comment by Kirek** [comment]
What about the output of 
sudo journalctl --unit=ntpd -r

**Comment by udeved** [comment]
Hmm, whih profile is it phil?

If it is xfce-minimal, iirc it lacks proper lightdm.conf. Not sure though.

Lightdm stars fine on openrc and autologin works too.

**Comment by manjaro** [comment]
Yes it is XFCE-minimal but also on XFCE we have this issue. Anyway I found the ntpd issue. It has something to do with groups file from overlay:
![systemd-error-ntp](https://cloud.githubusercontent.com/assets/5167332/5823526/c9c50a52-a0dd-11e4-8ba1-10868a68211f.jpg)

**Comment by udeved** [comment]
So the aufs doesn't merge properly? 
We probably have to play with rw mounting?

**Comment by Kirek** [comment]
Check if ntp user and group exist, and also lightdm user and group

**Comment by udeved** [comment]
What happens if we alter the isomounts order?
root.-image is last. atm.

**Comment by manjaro** [comment]
Mounting root as last is wrong. Totally. This explains lot of stuff going on wrong. We have to hold the mount order: root > de > pkgs > live. Now I know why pkgs image is so big and installs unneeded stuff.

**Comment by udeved** [comment]
lightdm and ntp group are created on desktop-image.

Wouldn't we need to mount desktop-image after root-image in isomounts and possibly livecd-image last?

**Comment by manjaro** [comment]
well livecd-image has group file of root-image !!!

Example for pkgs-image aufs mounts from manjaroiso:
<pre>              mount -t aufs -o br=${work_dir}/${image}:${work_dir}/root-image=ro none ${work_dir}/${image}
              if [ ! -z "${de}" ] ; then
                 echo -e -n "$_r >$_W mount ${desktop}-image \n $_n"
                 mount -t aufs -o remount,append:${work_dir}/${desktop}-image=ro none ${work_dir}/${image}
              fi</pre>

**Comment by manjaro** [comment]
isomounts is top-down order and correct. Has nothing to do with buildiso.

**Comment by udeved** [comment]
If we reorder, it would probably also fix the lightdm, which needs a special fix dunction.
I have always wondered about the order.

**Comment by udeved** [comment]
~~~
build_images(){
    load_pkgs_root
    make_image_root
    
    if [ -e "${pkgsfile}" ] ; then
	load_pkgs_de
	make_image_de
    fi

    if [ -e Packages-Xorg ] ; then
	load_pkgs_xorg
	make_image_xorg
    fi
    
    if [ -e Packages-Lng ] ; then
	load_pkgs_lng
	make_image_lng
    fi
    
    if [[ -f Packages-Livecd ]]; then
	load_pkgs_livecd
	make_image_livecd
    fi   
    
    make_image_boot
    if [ "${arch}" == "x86_64" ]; then
	make_efi
	make_efiboot
    fi
    make_isolinux
}
~~~

The order appears correct in the code if you mean that.

**Comment by manjaro** [comment]
I mean how we mount the images into the target. root is the downlayer, de is the middle layer and target is top layer.

**Comment by udeved** [comment]
This is how it works, but please review the aufs mount functions.

**Comment by udeved** [comment]
I think the isomounts file is wrong, last mount entry is top layer on iso, no?

**Comment by aadityabagga** [comment]
Today I built an ISO and got a size of 1 Gb whereas previously I was getting 690 Mb with manjaroiso...

I guess Philm's comment answers that.

**Comment by manjaro** [comment]
isomounts is correct. Nothing to change there. Problem is I was always mounting it wrongly. It should be like this:
<pre>[phil@manjaro x86_64]$ ls test
[phil@manjaro x86_64]$ sudo mount -t aufs -o br=test:xfce-image=ro none test[phil@manjaro x86_64]$ cat test/etc/group | grep ntp
ntp:x:87:
[phil@manjaro x86_64]$ sudo mount -t aufs -o remount,append:root-image=ro none test
[phil@manjaro x86_64]$ cat test/etc/group | grep ntpntp:x:87:
</pre>

**Comment by udeved** [comment]
so our aufs mount functions need to switch target and name.

**Comment by udeved** [comment]
~~~
# $1: add branch
aufs_append_root_image(){
    msg2 "mount ${desktop}-image"
#     mount -t aufs -o remount,append:${work_dir}/${desktop}-image=ro none $1
    mount -t aufs -o remount,append:${work_dir}/root-image=ro none $1
}

# $1: new branch
aufs_mount_desktop_image(){
    msg2 "mount root-image"
    mount -t aufs -o br=$1:${work_dir}/${desktop}-image=ro none $1
}
~~~

Like this phil?

**Comment by manjaro** [comment]
Like this: https://github.com/manjaro/manjaroiso/commit/f5f406ff6b883508944fc903005216f90226db50

**Comment by udeved** [comment]
Are you gonna make the changes to manjaro-tools too? Just asking to avoid merge conflicts.

**Comment by manjaro** [comment]
Might fix it 7b61ab137e5950c5972d47dea3c82366976e1ac7

**Comment by udeved** [comment]
I will test now.

Re aaditya iso size.

I get 705 MB for xfce minimal which seems good. I don't know iso size with manjarosio.

**Comment by manjaro** [comment]
704 is normal. This is what I got also. Should be same as with ManjaroISO.

**Comment by manjaro** [comment]
One error down. Now we have to deal with this lightdm network issue ;)
![systemd-error-lightdm](https://cloud.githubusercontent.com/assets/5167332/5824854/4b9e756e-a0e7-11e4-976f-0dbf0b84ecbd.jpg)

**Comment by udeved** [comment]
I commented out a plymout setting on root image, since I thought it gets configured on de image anyway.
This might be related, but you said it also doesn't work for normal lightdm without plymouth?

**Comment by udeved** [comment]
for xfce-minimal, the plymouth.conf looks fine on DE-image.

~~~
# Administrator customizations go in this file
[Daemon]
Theme=manjaro-elegant
~~~

and lightdm service is properly linked. Hmmm...

**Comment by udeved** [comment]
Phil, I see no plymouth hook in mkinitcpio.conf for xfce-minimal.

**Comment by manjaro** [comment]
Have to check this also. Might be the issue. This is the current issue:
![systemd-lightdm2](https://cloud.githubusercontent.com/assets/5167332/5825116/460bf980-a0e9-11e4-8de1-ff7619ec500f.jpg)

**Comment by manjaro** [comment]
Plymouth hook is now added with: https://github.com/manjaro/manjaro-tools-iso-profiles/commit/5ae916e4fef58633363a44f8ec2286d3fc6e2ab0

**Comment by udeved** [comment]
If plymouth is installed, buildido will link plymouth lightdm.

We could consider changing the displaymanager var to contain plymouth and get rid of the check in util-iso.

**Comment by manjaro** [comment]
displaymanager can never contain plymouth. Rather we add a var for has_plymouth or so. Calamares will break with displaymanager having plymouth in it.

**Comment by udeved** [comment]
Ah ok, what I mean, we should probably introduce a plymouth var, same idea.

This check in configure_displaymanager is ugly.

**Comment by manjaro** [comment]
Anyway, seems this issue with lightdm and network is really crazy. I don't know what causing it. If you unplug network in VirtualBox it boots up ... Hmm.

**Comment by udeved** [comment]
<a href='http://postimg.org/image/7k550x303/' target='_blank'><img src='http://s21.postimg.org/7k550x303/snap1.jpg' border='0' alt="snap1" /></a>

Something broke livecd and mhwd on openrc.

**Comment by udeved** [comment]
However, lightdm now seems to start without fix function, since autologin group is now known.

**Comment by udeved** [comment]
The last call in livecd script pulseaudio-ctl-normal fails.
 Livecd starts without this call.

**Comment by manjaro** [comment]
ok, I assume you fixed **pulseaudio-ctl-normal** for open-rc now ;) I'm still testing if the latest build works now for systemd ...

**Comment by udeved** [comment]
I removed some now useless lightdm fix which was fixed with new aufs mounting.

**Comment by manjaro** [comment]
Ok, it is fine. However lightdm still hangs if you have network enabled. Still can't pinpoint this issue. Seems not to be related to plymouth at all ...

![systemd-lightdm-network-issue](https://cloud.githubusercontent.com/assets/5167332/5828367/85a596f4-a103-11e4-8a79-3d08d5a340c1.jpg)

**Comment by udeved** [comment]
What greeter do you use?

Iirc, lightdm defaults to gtk2 if no greeter is specified.
Its perhaps a misconfiguration of lightdm.

What does the lightdm log say?

**Comment by manjaro** [comment]
Seems to be somehow X-Server related ...

![lightdm-xserver-issue](https://cloud.githubusercontent.com/assets/5167332/5828489/14a0ab72-a105-11e4-807e-3e928cc1e743.jpg)

Only happens if network is plugged. So no config issue.

**Comment by udeved** [comment]
It seems systemd specific.

**Comment by manjaro** [comment]
I think we should review my "fixes/quirks" I introduced cos of wrong aufs-mounting years ago. Most of the stuff is normally not needed. After a cleanup I can also remove those from Calamares and Thus ;)

**Comment by manjaro** [comment]
Hmm, I just tested it with VMWare Player and VirtualBox. Seems we have to disable Network before starting lightdm and autostart it in DE once again. Would be a workaround which might work.

**Comment by udeved** [comment]
Phil, should the autoloin group creation move to DE image, so that it gets installed?

**Comment by Kirek** [comment]
@manjaro can you modify the lightdm service (/usr/lib/systemd/system/lightdm.service) and add the switch "-d" in the ExecStart=, start it and see if it outputs a more useful log?

**Comment by manjaro** [comment]
@udeved: it is fine as it is now autologin group is part of functions and installers. Don't worry. Works as it is.

@Kirek: will do that after 0.8.12-rc1 release.

**Comment by manjaro** [comment]
I [removed some tmpfiles.d file](https://github.com/manjaro/manjaro-tools-iso-profiles/commit/2fe45dde859e957af0aa9655e67e0fa3466f30d6) and was able now to bootup the image even with network on. However, on VMWare-Player and Virtualbox on my work laptop it still blocks. Might be also related to our proxy settings at work ...

**Comment by udeved** [comment]
Would we be fine closing this?

I thought a 0.9.6.1 would be good.

**Comment by udeved** [comment]
I still don't quite understand why this open dbus process occurs in chroot, and if this is probably related to the systemd network troubles with lightdm?

**Comment by manjaro** [comment]
Which DBUS error?

**Comment by udeved** [comment]
I mean the dbus processes we kill as workaround.

**Comment by manjaro** [comment]
Only if needed. This issue has nothing to do with this problem we are facing here. For me the network turnoff in systemd "fixes" the issue we have with lightdm. I'll release 0.9.0-pre2 today. We can reopen this issue when we find time to investigate it once more ...

**Comment by manjaro** [comment]
Forum posts which might still related on this issue:
https://forum.manjaro.org/index.php?topic=16191.msg178278#msg178278
https://forum.manjaro.org/index.php?topic=16191.msg178315#msg178315
https://forum.manjaro.org/index.php?topic=16191.msg178341#msg178341
https://forum.manjaro.org/index.php?topic=16191.msg179640#msg179640

**Comment by manjaro** [comment]
might be related to mhwd-live.service ... Investigating.

**Comment by udeved** [comment]
https://forum.manjaro.org/index.php?topic=19869.msg179845

Have you seen this?

**Comment by manjaro** [comment]
@udeved: not related. It is related to https://github.com/manjaro/pamac/issues/25

**Comment by manjaro** [comment]
... it might be also releated to some other systemd services handling pacman. At least I can pinpoint it to a locked database.

**Comment by udeved** [comment]
Does it also occur if you add NM to DE-image services as opposed to default livecd image?
I guess so? Have you tested this?

**Comment by manjaro** [comment]
Well some gets triggered which locks the pacman database. I assume it is pamac daemon as we have a similar issue there. Anyway it is good to remove database lock before installing, that is why I added this 15sec delay. The trigger is somehow related to network. When do drivers got installed by mhwd the displaymanager hangs. This is a fact. I think placing NM to DE-images will make no difference. Why was it placed to livecd image anyway?

**Comment by udeved** [comment]
I thought installer would handle network connection.
I can change it quickly.

**Comment by manjaro** [comment]
Installer handle that. So don't worry.

**Comment by udeved** [comment]
I had some testing with xfce-minimal yesterday.

I tnotice that pamach didn't start.
But, I also noticed,  that the pacman-boot script was still installed but wasn't started.

    systemctl --all 

did show it.

Does pacman-boot clash with pamac?

As result, the iso did not have a networkconnection in DE session. I had to restart NM service.

**Comment by manjaro** [comment]
I fixed just two hours ago with 72aee34497f5e525792cd9ff4be241c34ddf8745

**Comment by udeved** [comment]
Ok, already build new pkg from your commit.

But what about pacman-boot? Did you update the livecd packages in repo with removed pacman-boot?
Haven't checked yet.

**Comment by manjaro** [comment]
0.9.0-pre2 has no pacman-boot on it. Last bootup didn't clash with anything. I did a re-upload of that release. Expect a new 0.9.0-dev later on.
